# Generated by Django 6.0.5 on 2026-05-16 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emhana', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='speciality',
            new_name='specialty',
        ),
    ]
