# Generated by Django 6.0.5 on 2026-05-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emhana', '0002_rename_speciality_doctor_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Жалобы/Заметки'),
        ),
    ]
